//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMenu
    {
        public int Id { get; set; }
        public int IdMenu { get; set; }
        public int Count { get; set; }
        public int IdOrder { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
